///////////////////////////////////////////////////////////
//  CFGASIENTOTRN_D.cs
//  Implementation of the Class CFGASIENTOTRN_D
//  Generated by Enterprise Architect
//  Created on:      01-nov-2018 09:54:30 p.m.
//  Original author: User
///////////////////////////////////////////////////////////




using Contabilidad;
namespace Contabilidad {
	public class CFGASIENTOTRN_D {

		private int cntcfgasitrnid;
        private string cntctano;
        private int cnttrnop;
        private int cntrubid;
	

		public CFGASIENTOTRN_D(){

		}

		~CFGASIENTOTRN_D(){

		}

		public virtual void Dispose(){

		}

		public int Cntcfgasitrnid{
			get{
				return cntcfgasitrnid;
			}
			set{
				cntcfgasitrnid = value;
			}
		}

		public string Cntctano{
			get{
				return cntctano;
			}
			set{
				cntctano = value;
			}
		}

		public int Cnttrnop{
			get{
				return cnttrnop;
			}
			set{
				cnttrnop = value;
			}
		}

		public int Cntrubid{
			get{
				return cntrubid;
			}
			set{
				cntrubid = value;
			}
		}

	}//end CFGASIENTOTRN_D

}//end namespace Contabilidad