///////////////////////////////////////////////////////////
//  CFGASIENTOTRN_M.cs
//  Implementation of the Class CFGASIENTOTRN_M
//  Generated by Enterprise Architect
//  Created on:      01-nov-2018 09:54:30 p.m.
//  Original author: User
///////////////////////////////////////////////////////////




using Contabilidad;
namespace Contabilidad {
	public class CFGASIENTOTRN_M {

        private int cntcfgasitrnid;
        private int cnttrnid;
        private int cnttiptrnid;
		

		public CFGASIENTOTRN_M(){

		}

		~CFGASIENTOTRN_M(){

		}

		public virtual void Dispose(){

		}

		public int Cntcfgasitrnid{
			get{
				return cntcfgasitrnid;
			}
			set{
				cntcfgasitrnid = value;
			}
		}

		public int Cnttrnid{
			get{
				return cnttrnid;
			}
			set{
				cnttrnid = value;
			}
		}

		public int Cnttiptrnid{
			get{
				return cnttiptrnid;
			}
			set{
				cnttiptrnid = value;
			}
		}

	}//end CFGASIENTOTRN_M

}//end namespace Contabilidad