///////////////////////////////////////////////////////////
//  CUENTAS.cs
//  Implementation of the Class CUENTAS
//  Generated by Enterprise Architect
//  Created on:      01-nov-2018 09:54:30 p.m.
//  Original author: User
///////////////////////////////////////////////////////////




namespace Contabilidad.model {
	public class CUENTAS {

        private string cntctano;
        private string cntctanom;
        private char cntctatipo;
        private string cntctama;

		public CUENTAS(){

		}

		~CUENTAS(){

		}

		public virtual void Dispose(){

		}

		public char Cntctatipo{
			get{
				return cntctatipo;
			}
			set{
				cntctatipo = value;
			}
		}

		public string Cntctanom{
			get{
				return cntctanom;
			}
			set{
				cntctanom = value;
			}
		}

		public string Cntctano{
			get{
				return cntctano;
			}
			set{
				cntctano = value;
			}
		}
        public string Cntctama
        {
            get
            {
                return cntctama;
            }
            set
            {
                cntctama = value;
            }
        }

	}//end CUENTAS

}//end namespace Contabilidad