///////////////////////////////////////////////////////////
//  RUBROS.cs
//  Implementation of the Class RUBROS
//  Generated by Enterprise Architect
//  Created on:      01-nov-2018 09:54:31 p.m.
//  Original author: User
///////////////////////////////////////////////////////////




namespace Contabilidad {
	public class RUBROS {

        private int cntrubid;
        private string cntrubnom;

		public RUBROS(){

		}

		~RUBROS(){

		}

		public virtual void Dispose(){

		}

		public int Cntrubid{
			get{
				return cntrubid;
			}
			set{
				cntrubid = value;
			}
		}

		public string Cntrubnom{
			get{
				return cntrubnom;
			}
			set{
				cntrubnom = value;
			}
		}

	}//end RUBROS

}//end namespace Contabilidad