///////////////////////////////////////////////////////////
//  TRNASIENTO.cs
//  Implementation of the Class TRNASIENTO
//  Generated by Enterprise Architect
//  Created on:      01-nov-2018 09:54:31 p.m.
//  Original author: User
///////////////////////////////////////////////////////////




using Contabilidad;
namespace Contabilidad {
	public class TRNASIENTO {

        private int cnttrnid;
        private string cntctano;
        private decimal cntasivalor;
        private int cntasiop;
	

		public TRNASIENTO(){

		}

		~TRNASIENTO(){

		}

		public virtual void Dispose(){

		}

		public int Cnttrnid{
			get{
				return cnttrnid;
			}
			set{
				cnttrnid = value;
			}
		}

		public string Cntctano{
			get{
				return cntctano;
			}
			set{
				cntctano = value;
			}
		}

		public decimal Cntasivalor{
			get{
				return cntasivalor;
			}
			set{
				cntasivalor = value;
			}
		}

		public int Cntasiop{
			get{
				return cntasiop;
			}
			set{
				cntasiop = value;
			}
		}

	}//end TRNASIENTO

}//end namespace Contabilidad